//File Automatically generated by SystemC Netlister Time
#include "vitis_design_sci.h"
vitis_design_sci::vitis_design_sci(const sc_module_name& module_name) : xsc::utils::xsc_sim_conn_base(module_name) 
{
	//Exported sockets Instantiation
	//Add TLM Parameters
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0","M01_AXI_TLM_MODE","vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0","M01_AXI_TLM_MODE","vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_imp_auto_cc_1","M_AXI_TLM_MODE","vitis_design_interconnect_axilite_imp_m02_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_imp_auto_cc_1","M_AXI_TLM_MODE","vitis_design_interconnect_axilite_imp_m02_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0","M01_AXI_TLM_MODE","vitis_design_interconnect_axilite_imp_auto_cc_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0","M01_AXI_TLM_MODE","vitis_design_interconnect_axilite_imp_auto_cc_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0","M02_AXI_TLM_MODE","vitis_design_interconnect_axilite_imp_auto_cc_1","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0","M02_AXI_TLM_MODE","vitis_design_interconnect_axilite_imp_auto_cc_1","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M00_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M00_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M01_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M01_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M02_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M02_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M03_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0","M03_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_hub_0","S_AXIFIFO_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_hub_0","S_AXIFIFO_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_hub_0","S_AXIHUB_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_hub_0","S_AXIHUB_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_mon0_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_mon0_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_mon0_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_mon0_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon0_0_0","TRACE_OUT_0_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_0_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon0_0_0","TRACE_OUT_1_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_1_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon0_1_0","TRACE_OUT_0_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_2_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon0_1_0","TRACE_OUT_1_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_3_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_imp_m02_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axilite_imp_m02_regslice_0","M_AXI_TLM_MODE","vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_ps_e_0","M_AXI_HPM0_LPD_tlm_MODE","vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_ps_e_0","M_AXI_HPM0_LPD_tlm_MODE","vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0","M00_AXI_TLM_MODE","vitis_design_axi_register_slice_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0","M00_AXI_TLM_MODE","vitis_design_axi_register_slice_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_axi_vip_1_0","M_AXI_TLM_MODE","vitis_design_ps_e_0","S_AXI_LPD_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_axi_vip_1_0","M_AXI_TLM_MODE","vitis_design_ps_e_0","S_AXI_LPD_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_ps_e_0","M_AXI_HPM0_FPD_tlm_MODE","vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_ps_e_0","M_AXI_HPM0_FPD_tlm_MODE","vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0","S00_AXI_TLM_MODE",1);
	
	xsc::utils::xsc_sim_manager::addInstance("vitis_design_sci", this);
	#if defined MTI_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()) {
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	scv_startup(); /* Initialize SCV: */
	scv_tr_wlf_init(); /* Tie databases to WLF: */
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
	#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()){
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	cve_tr_sdi_init();
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
}
vitis_design_sci::~vitis_design_sci()
{
}
void vitis_design_sci::initConnModule() {

}

void vitis_design_sci::before_end_of_elaboration() {
	
	vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*  inst_0=dynamic_cast<vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0"));
	vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_sc*  inst_1=dynamic_cast<vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0"));
	xtlm_aximm_transaction_logger* log_inst_0 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_0");
	log_inst_0->setProxyRef(inst_0, inst_1, "vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_M01_AXI_TLM", "vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_S_AXI_TLM", log_inst_0->m_transactionLogger);
	
	if(inst_0==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_1==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_sc"<<std::endl;
	}
	
	if (inst_0!=NULL && inst_1!=NULL) {
		inst_0->initiator_1_rd_socket->bind(*(log_inst_0->tar_rd_skt));
		log_inst_0->init_rd_skt->bind(*(inst_1->S_TARGET_rd_socket));
	}
	
	vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*  inst_4=dynamic_cast<vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0"));
	vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_sc*  inst_5=dynamic_cast<vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0"));
	
	if(inst_4==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_5==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_imp_auto_cc_0_sc"<<std::endl;
	}
	
	if (inst_4!=NULL && inst_5!=NULL) {
		inst_4->initiator_1_wr_socket->bind(*(log_inst_0->tar_wr_skt));
		log_inst_0->init_wr_skt->bind(*(inst_5->S_TARGET_wr_socket));
	}
	
	vitis_design_interconnect_axilite_imp_auto_cc_1_sc*  inst_8=dynamic_cast<vitis_design_interconnect_axilite_imp_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_auto_cc_1"));
	vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*  inst_9=dynamic_cast<vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_m02_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_1 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_1");
	log_inst_1->setProxyRef(inst_8, inst_9, "vitis_design_interconnect_axilite_imp_auto_cc_1_M_AXI_TLM", "vitis_design_interconnect_axilite_imp_m02_regslice_0_S_AXI_TLM", log_inst_1->m_transactionLogger);
	
	if(inst_8==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_auto_cc_1_sc"<<std::endl;
	}
	if(inst_9==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_m02_regslice_0_sc"<<std::endl;
	}
	
	if (inst_8!=NULL && inst_9!=NULL) {
		inst_8->M_INITIATOR_rd_socket->bind(*(log_inst_1->tar_rd_skt));
		log_inst_1->init_rd_skt->bind(*(inst_9->S_TARGET_rd_socket));
	}
	
	vitis_design_interconnect_axilite_imp_auto_cc_1_sc*  inst_12=dynamic_cast<vitis_design_interconnect_axilite_imp_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_auto_cc_1"));
	vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*  inst_13=dynamic_cast<vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_m02_regslice_0"));
	
	if(inst_12==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_auto_cc_1_sc"<<std::endl;
	}
	if(inst_13==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_m02_regslice_0_sc"<<std::endl;
	}
	
	if (inst_12!=NULL && inst_13!=NULL) {
		inst_12->M_INITIATOR_wr_socket->bind(*(log_inst_1->tar_wr_skt));
		log_inst_1->init_wr_skt->bind(*(inst_13->S_TARGET_wr_socket));
	}
	
	vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*  inst_16=dynamic_cast<vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0"));
	vitis_design_interconnect_axilite_imp_auto_cc_0_sc*  inst_17=dynamic_cast<vitis_design_interconnect_axilite_imp_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_auto_cc_0"));
	xtlm_aximm_transaction_logger* log_inst_2 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_2");
	log_inst_2->setProxyRef(inst_16, inst_17, "vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_M01_AXI_TLM", "vitis_design_interconnect_axilite_imp_auto_cc_0_S_AXI_TLM", log_inst_2->m_transactionLogger);
	
	if(inst_16==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_17==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_auto_cc_0_sc"<<std::endl;
	}
	
	if (inst_16!=NULL && inst_17!=NULL) {
		inst_16->initiator_1_rd_socket->bind(*(log_inst_2->tar_rd_skt));
		log_inst_2->init_rd_skt->bind(*(inst_17->S_TARGET_rd_socket));
	}
	
	vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*  inst_20=dynamic_cast<vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0"));
	vitis_design_interconnect_axilite_imp_auto_cc_0_sc*  inst_21=dynamic_cast<vitis_design_interconnect_axilite_imp_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_auto_cc_0"));
	
	if(inst_20==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_21==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_auto_cc_0_sc"<<std::endl;
	}
	
	if (inst_20!=NULL && inst_21!=NULL) {
		inst_20->initiator_1_wr_socket->bind(*(log_inst_2->tar_wr_skt));
		log_inst_2->init_wr_skt->bind(*(inst_21->S_TARGET_wr_socket));
	}
	
	vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*  inst_24=dynamic_cast<vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0"));
	vitis_design_interconnect_axilite_imp_auto_cc_1_sc*  inst_25=dynamic_cast<vitis_design_interconnect_axilite_imp_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_auto_cc_1"));
	xtlm_aximm_transaction_logger* log_inst_3 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_3");
	log_inst_3->setProxyRef(inst_24, inst_25, "vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_M02_AXI_TLM", "vitis_design_interconnect_axilite_imp_auto_cc_1_S_AXI_TLM", log_inst_3->m_transactionLogger);
	
	if(inst_24==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_25==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_auto_cc_1_sc"<<std::endl;
	}
	
	if (inst_24!=NULL && inst_25!=NULL) {
		inst_24->initiator_2_rd_socket->bind(*(log_inst_3->tar_rd_skt));
		log_inst_3->init_rd_skt->bind(*(inst_25->S_TARGET_rd_socket));
	}
	
	vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*  inst_28=dynamic_cast<vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0"));
	vitis_design_interconnect_axilite_imp_auto_cc_1_sc*  inst_29=dynamic_cast<vitis_design_interconnect_axilite_imp_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_auto_cc_1"));
	
	if(inst_28==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_29==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_auto_cc_1_sc"<<std::endl;
	}
	
	if (inst_28!=NULL && inst_29!=NULL) {
		inst_28->initiator_2_wr_socket->bind(*(log_inst_3->tar_wr_skt));
		log_inst_3->init_wr_skt->bind(*(inst_29->S_TARGET_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_32=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*  inst_33=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_4 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_4");
	log_inst_4->setProxyRef(inst_32, inst_33, "vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_M00_AXI_TLM", "vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_S_AXI_TLM", log_inst_4->m_transactionLogger);
	
	if(inst_32==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_33==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_32!=NULL && inst_33!=NULL) {
		inst_32->initiator_0_rd_socket->bind(*(log_inst_4->tar_rd_skt));
		log_inst_4->init_rd_skt->bind(*(inst_33->S_TARGET_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_36=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*  inst_37=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0"));
	
	if(inst_36==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_37==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_36!=NULL && inst_37!=NULL) {
		inst_36->initiator_0_wr_socket->bind(*(log_inst_4->tar_wr_skt));
		log_inst_4->init_wr_skt->bind(*(inst_37->S_TARGET_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_40=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*  inst_41=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_5 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_5");
	log_inst_5->setProxyRef(inst_40, inst_41, "vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_M01_AXI_TLM", "vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_S_AXI_TLM", log_inst_5->m_transactionLogger);
	
	if(inst_40==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_41==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc"<<std::endl;
	}
	
	if (inst_40!=NULL && inst_41!=NULL) {
		inst_40->initiator_1_rd_socket->bind(*(log_inst_5->tar_rd_skt));
		log_inst_5->init_rd_skt->bind(*(inst_41->S_TARGET_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_44=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*  inst_45=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0"));
	
	if(inst_44==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_45==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc"<<std::endl;
	}
	
	if (inst_44!=NULL && inst_45!=NULL) {
		inst_44->initiator_1_wr_socket->bind(*(log_inst_5->tar_wr_skt));
		log_inst_5->init_wr_skt->bind(*(inst_45->S_TARGET_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_48=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*  inst_49=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_6 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_6");
	log_inst_6->setProxyRef(inst_48, inst_49, "vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_M02_AXI_TLM", "vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_S_AXI_TLM", log_inst_6->m_transactionLogger);
	
	if(inst_48==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_49==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc"<<std::endl;
	}
	
	if (inst_48!=NULL && inst_49!=NULL) {
		inst_48->initiator_2_rd_socket->bind(*(log_inst_6->tar_rd_skt));
		log_inst_6->init_rd_skt->bind(*(inst_49->S_TARGET_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_52=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*  inst_53=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0"));
	
	if(inst_52==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_53==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc"<<std::endl;
	}
	
	if (inst_52!=NULL && inst_53!=NULL) {
		inst_52->initiator_2_wr_socket->bind(*(log_inst_6->tar_wr_skt));
		log_inst_6->init_wr_skt->bind(*(inst_53->S_TARGET_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_56=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*  inst_57=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_7 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_7");
	log_inst_7->setProxyRef(inst_56, inst_57, "vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_M03_AXI_TLM", "vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_S_AXI_TLM", log_inst_7->m_transactionLogger);
	
	if(inst_56==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_57==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc"<<std::endl;
	}
	
	if (inst_56!=NULL && inst_57!=NULL) {
		inst_56->initiator_3_rd_socket->bind(*(log_inst_7->tar_rd_skt));
		log_inst_7->init_rd_skt->bind(*(inst_57->S_TARGET_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*  inst_60=dynamic_cast<vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0"));
	vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*  inst_61=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0"));
	
	if(inst_60==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_61==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc"<<std::endl;
	}
	
	if (inst_60!=NULL && inst_61!=NULL) {
		inst_60->initiator_3_wr_socket->bind(*(log_inst_7->tar_wr_skt));
		log_inst_7->init_wr_skt->bind(*(inst_61->S_TARGET_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*  inst_64=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0"));
	vitis_design_dpa_hub_0_sc*  inst_65=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_8 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_8");
	log_inst_8->setProxyRef(inst_64, inst_65, "vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_M_AXI_TLM", "vitis_design_dpa_hub_0_S_AXIFIFO_TLM", log_inst_8->m_transactionLogger);
	
	if(inst_64==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc"<<std::endl;
	}
	if(inst_65==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_64!=NULL && inst_65!=NULL) {
		inst_64->M_INITIATOR_rd_socket->bind(*(log_inst_8->tar_rd_skt));
		log_inst_8->init_rd_skt->bind(*(inst_65->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*  inst_68=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0"));
	vitis_design_dpa_hub_0_sc*  inst_69=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	
	if(inst_68==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m00_regslice_0_sc"<<std::endl;
	}
	if(inst_69==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_68!=NULL && inst_69!=NULL) {
		inst_68->M_INITIATOR_wr_socket->bind(*(log_inst_8->tar_wr_skt));
		log_inst_8->init_wr_skt->bind(*(inst_69->axilite_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*  inst_72=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0"));
	vitis_design_dpa_hub_0_sc*  inst_73=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_9 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_9");
	log_inst_9->setProxyRef(inst_72, inst_73, "vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_M_AXI_TLM", "vitis_design_dpa_hub_0_S_AXIHUB_TLM", log_inst_9->m_transactionLogger);
	
	if(inst_72==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc"<<std::endl;
	}
	if(inst_73==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_72!=NULL && inst_73!=NULL) {
		inst_72->M_INITIATOR_rd_socket->bind(*(log_inst_9->tar_rd_skt));
		log_inst_9->init_rd_skt->bind(*(inst_73->s_axihub_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*  inst_76=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0"));
	vitis_design_dpa_hub_0_sc*  inst_77=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	
	if(inst_76==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m01_regslice_0_sc"<<std::endl;
	}
	if(inst_77==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_76!=NULL && inst_77!=NULL) {
		inst_76->M_INITIATOR_wr_socket->bind(*(log_inst_9->tar_wr_skt));
		log_inst_9->init_wr_skt->bind(*(inst_77->s_axihub_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*  inst_80=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0"));
	vitis_design_dpa_mon0_0_0_sc*  inst_81=dynamic_cast<vitis_design_dpa_mon0_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0_0"));
	xtlm_aximm_transaction_logger* log_inst_10 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_10");
	log_inst_10->setProxyRef(inst_80, inst_81, "vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_M_AXI_TLM", "vitis_design_dpa_mon0_0_0_S_AXI_TLM", log_inst_10->m_transactionLogger);
	
	if(inst_80==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc"<<std::endl;
	}
	if(inst_81==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_0_sc"<<std::endl;
	}
	
	if (inst_80!=NULL && inst_81!=NULL) {
		inst_80->M_INITIATOR_rd_socket->bind(*(log_inst_10->tar_rd_skt));
		log_inst_10->init_rd_skt->bind(*(inst_81->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*  inst_84=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0"));
	vitis_design_dpa_mon0_0_0_sc*  inst_85=dynamic_cast<vitis_design_dpa_mon0_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0_0"));
	
	if(inst_84==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m02_regslice_0_sc"<<std::endl;
	}
	if(inst_85==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_0_sc"<<std::endl;
	}
	
	if (inst_84!=NULL && inst_85!=NULL) {
		inst_84->M_INITIATOR_wr_socket->bind(*(log_inst_10->tar_wr_skt));
		log_inst_10->init_wr_skt->bind(*(inst_85->axilite_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*  inst_88=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0"));
	vitis_design_dpa_mon0_1_0_sc*  inst_89=dynamic_cast<vitis_design_dpa_mon0_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_1_0"));
	xtlm_aximm_transaction_logger* log_inst_11 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_11");
	log_inst_11->setProxyRef(inst_88, inst_89, "vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_M_AXI_TLM", "vitis_design_dpa_mon0_1_0_S_AXI_TLM", log_inst_11->m_transactionLogger);
	
	if(inst_88==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc"<<std::endl;
	}
	if(inst_89==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_1_0_sc"<<std::endl;
	}
	
	if (inst_88!=NULL && inst_89!=NULL) {
		inst_88->M_INITIATOR_rd_socket->bind(*(log_inst_11->tar_rd_skt));
		log_inst_11->init_rd_skt->bind(*(inst_89->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*  inst_92=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0"));
	vitis_design_dpa_mon0_1_0_sc*  inst_93=dynamic_cast<vitis_design_dpa_mon0_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_1_0"));
	
	if(inst_92==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_m03_regslice_0_sc"<<std::endl;
	}
	if(inst_93==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_1_0_sc"<<std::endl;
	}
	
	if (inst_92!=NULL && inst_93!=NULL) {
		inst_92->M_INITIATOR_wr_socket->bind(*(log_inst_11->tar_wr_skt));
		log_inst_11->init_wr_skt->bind(*(inst_93->axilite_wr_socket));
	}
	
	vitis_design_dpa_mon0_0_0_sc*  inst_96=dynamic_cast<vitis_design_dpa_mon0_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0_0"));
	vitis_design_dpa_hub_0_sc*  inst_97=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_12 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_12");
	log_inst_12->setProxyRef(inst_96, inst_97, "vitis_design_dpa_mon0_0_0_TRACE_OUT_0_TLM", "vitis_design_dpa_hub_0_TRACE_IN_0_TLM", log_inst_12->m_transactionLogger);
	
	if(inst_96==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_0_sc"<<std::endl;
	}
	if(inst_97==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_96!=NULL && inst_97!=NULL) {
		inst_96->wr_trace_socket->bind(*(log_inst_12->tar_skt));
		log_inst_12->init_skt->bind(*(inst_97->trace_socket0));
	}
	
	vitis_design_dpa_mon0_0_0_sc*  inst_100=dynamic_cast<vitis_design_dpa_mon0_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0_0"));
	vitis_design_dpa_hub_0_sc*  inst_101=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_13 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_13");
	log_inst_13->setProxyRef(inst_100, inst_101, "vitis_design_dpa_mon0_0_0_TRACE_OUT_1_TLM", "vitis_design_dpa_hub_0_TRACE_IN_1_TLM", log_inst_13->m_transactionLogger);
	
	if(inst_100==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_0_sc"<<std::endl;
	}
	if(inst_101==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_100!=NULL && inst_101!=NULL) {
		inst_100->rd_trace_socket->bind(*(log_inst_13->tar_skt));
		log_inst_13->init_skt->bind(*(inst_101->trace_socket1));
	}
	
	vitis_design_dpa_mon0_1_0_sc*  inst_104=dynamic_cast<vitis_design_dpa_mon0_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_1_0"));
	vitis_design_dpa_hub_0_sc*  inst_105=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_14 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_14");
	log_inst_14->setProxyRef(inst_104, inst_105, "vitis_design_dpa_mon0_1_0_TRACE_OUT_0_TLM", "vitis_design_dpa_hub_0_TRACE_IN_2_TLM", log_inst_14->m_transactionLogger);
	
	if(inst_104==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_1_0_sc"<<std::endl;
	}
	if(inst_105==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_104!=NULL && inst_105!=NULL) {
		inst_104->wr_trace_socket->bind(*(log_inst_14->tar_skt));
		log_inst_14->init_skt->bind(*(inst_105->trace_socket2));
	}
	
	vitis_design_dpa_mon0_1_0_sc*  inst_108=dynamic_cast<vitis_design_dpa_mon0_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_1_0"));
	vitis_design_dpa_hub_0_sc*  inst_109=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_15 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_15");
	log_inst_15->setProxyRef(inst_108, inst_109, "vitis_design_dpa_mon0_1_0_TRACE_OUT_1_TLM", "vitis_design_dpa_hub_0_TRACE_IN_3_TLM", log_inst_15->m_transactionLogger);
	
	if(inst_108==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_1_0_sc"<<std::endl;
	}
	if(inst_109==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_108!=NULL && inst_109!=NULL) {
		inst_108->rd_trace_socket->bind(*(log_inst_15->tar_skt));
		log_inst_15->init_skt->bind(*(inst_109->trace_socket3));
	}
	
	vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_sc*  inst_112=dynamic_cast<vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0"));
	vitis_design_dpa_hub_0_sc*  inst_113=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_16 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_16");
	log_inst_16->setProxyRef(inst_112, inst_113, "vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_M_AXI_TLM", "vitis_design_dpa_hub_0_S_AXIMM_TLM", log_inst_16->m_transactionLogger);
	
	if(inst_112==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_sc"<<std::endl;
	}
	if(inst_113==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_112!=NULL && inst_113!=NULL) {
		inst_112->M_INITIATOR_rd_socket->bind(*(log_inst_16->tar_rd_skt));
		log_inst_16->init_rd_skt->bind(*(inst_113->s_aximm_rd_socket));
	}
	
	vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_sc*  inst_116=dynamic_cast<vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0"));
	vitis_design_dpa_hub_0_sc*  inst_117=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	
	if(inst_116==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_imp_m01_regslice_0_sc"<<std::endl;
	}
	if(inst_117==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_116!=NULL && inst_117!=NULL) {
		inst_116->M_INITIATOR_wr_socket->bind(*(log_inst_16->tar_wr_skt));
		log_inst_16->init_wr_skt->bind(*(inst_117->s_aximm_wr_socket));
	}
	
	vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*  inst_120=dynamic_cast<vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_m02_regslice_0"));
	vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_sc*  inst_121=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_17 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_17");
	log_inst_17->setProxyRef(inst_120, inst_121, "vitis_design_interconnect_axilite_imp_m02_regslice_0_M_AXI_TLM", "vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_S_AXI_TLM", log_inst_17->m_transactionLogger);
	
	if(inst_120==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_m02_regslice_0_sc"<<std::endl;
	}
	if(inst_121==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_120!=NULL && inst_121!=NULL) {
		inst_120->M_INITIATOR_rd_socket->bind(*(log_inst_17->tar_rd_skt));
		log_inst_17->init_rd_skt->bind(*(inst_121->S_TARGET_rd_socket));
	}
	
	vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*  inst_124=dynamic_cast<vitis_design_interconnect_axilite_imp_m02_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_imp_m02_regslice_0"));
	vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_sc*  inst_125=dynamic_cast<vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0"));
	
	if(inst_124==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_imp_m02_regslice_0_sc"<<std::endl;
	}
	if(inst_125==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_imp_s00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_124!=NULL && inst_125!=NULL) {
		inst_124->M_INITIATOR_wr_socket->bind(*(log_inst_17->tar_wr_skt));
		log_inst_17->init_wr_skt->bind(*(inst_125->S_TARGET_wr_socket));
	}
	
	vitis_design_ps_e_0_sc*  inst_128=dynamic_cast<vitis_design_ps_e_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ps_e_0"));
	vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*  inst_129=dynamic_cast<vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0"));
	xtlm_aximm_transaction_logger* log_inst_18 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_18");
	log_inst_18->setProxyRef(inst_128, inst_129, "vitis_design_ps_e_0_M_AXI_HPM0_LPD_tlm", "vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_S00_AXI_TLM", log_inst_18->m_transactionLogger);
	
	if(inst_128==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ps_e_0_sc"<<std::endl;
	}
	if(inst_129==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	
	if (inst_128!=NULL && inst_129!=NULL) {
		inst_128->M_AXI_HPM0_LPD_rd_socket->bind(*(log_inst_18->tar_rd_skt));
		log_inst_18->init_rd_skt->bind(*(inst_129->target_0_rd_socket));
	}
	
	vitis_design_ps_e_0_sc*  inst_132=dynamic_cast<vitis_design_ps_e_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ps_e_0"));
	vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*  inst_133=dynamic_cast<vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0"));
	
	if(inst_132==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ps_e_0_sc"<<std::endl;
	}
	if(inst_133==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axilite_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	
	if (inst_132!=NULL && inst_133!=NULL) {
		inst_132->M_AXI_HPM0_LPD_wr_socket->bind(*(log_inst_18->tar_wr_skt));
		log_inst_18->init_wr_skt->bind(*(inst_133->target_0_wr_socket));
	}
	
	vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*  inst_136=dynamic_cast<vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0"));
	vitis_design_axi_register_slice_0_0_sc*  inst_137=dynamic_cast<vitis_design_axi_register_slice_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_axi_register_slice_0_0"));
	xtlm_aximm_transaction_logger* log_inst_19 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_19");
	log_inst_19->setProxyRef(inst_136, inst_137, "vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_M00_AXI_TLM", "vitis_design_axi_register_slice_0_0_S_AXI_TLM", log_inst_19->m_transactionLogger);
	
	if(inst_136==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_137==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_axi_register_slice_0_0_sc"<<std::endl;
	}
	
	if (inst_136!=NULL && inst_137!=NULL) {
		inst_136->initiator_0_rd_socket->bind(*(log_inst_19->tar_rd_skt));
		log_inst_19->init_rd_skt->bind(*(inst_137->S_TARGET_rd_socket));
	}
	
	vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*  inst_140=dynamic_cast<vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0"));
	vitis_design_axi_register_slice_0_0_sc*  inst_141=dynamic_cast<vitis_design_axi_register_slice_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_axi_register_slice_0_0"));
	
	if(inst_140==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	if(inst_141==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_axi_register_slice_0_0_sc"<<std::endl;
	}
	
	if (inst_140!=NULL && inst_141!=NULL) {
		inst_140->initiator_0_wr_socket->bind(*(log_inst_19->tar_wr_skt));
		log_inst_19->init_wr_skt->bind(*(inst_141->S_TARGET_wr_socket));
	}
	
	vitis_design_axi_vip_1_0_sc*  inst_144=dynamic_cast<vitis_design_axi_vip_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_axi_vip_1_0"));
	vitis_design_ps_e_0_sc*  inst_145=dynamic_cast<vitis_design_ps_e_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ps_e_0"));
	xtlm_aximm_transaction_logger* log_inst_20 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_20");
	log_inst_20->setProxyRef(inst_144, inst_145, "vitis_design_axi_vip_1_0_M_AXI_TLM", "vitis_design_ps_e_0_S_AXI_LPD_tlm", log_inst_20->m_transactionLogger);
	
	if(inst_144==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_axi_vip_1_0_sc"<<std::endl;
	}
	if(inst_145==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ps_e_0_sc"<<std::endl;
	}
	
	if (inst_144!=NULL && inst_145!=NULL) {
		inst_144->M_INITIATOR_rd_socket->bind(*(log_inst_20->tar_rd_skt));
		log_inst_20->init_rd_skt->bind(*(inst_145->S_AXI_LPD_rd_socket));
	}
	
	vitis_design_axi_vip_1_0_sc*  inst_148=dynamic_cast<vitis_design_axi_vip_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_axi_vip_1_0"));
	vitis_design_ps_e_0_sc*  inst_149=dynamic_cast<vitis_design_ps_e_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ps_e_0"));
	
	if(inst_148==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_axi_vip_1_0_sc"<<std::endl;
	}
	if(inst_149==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ps_e_0_sc"<<std::endl;
	}
	
	if (inst_148!=NULL && inst_149!=NULL) {
		inst_148->M_INITIATOR_wr_socket->bind(*(log_inst_20->tar_wr_skt));
		log_inst_20->init_wr_skt->bind(*(inst_149->S_AXI_LPD_wr_socket));
	}
	
	vitis_design_ps_e_0_sc*  inst_152=dynamic_cast<vitis_design_ps_e_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ps_e_0"));
	vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*  inst_153=dynamic_cast<vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0"));
	xtlm_aximm_transaction_logger* log_inst_21 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_21");
	log_inst_21->setProxyRef(inst_152, inst_153, "vitis_design_ps_e_0_M_AXI_HPM0_FPD_tlm", "vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_S00_AXI_TLM", log_inst_21->m_transactionLogger);
	
	if(inst_152==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ps_e_0_sc"<<std::endl;
	}
	if(inst_153==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	
	if (inst_152!=NULL && inst_153!=NULL) {
		inst_152->M_AXI_HPM0_FPD_rd_socket->bind(*(log_inst_21->tar_rd_skt));
		log_inst_21->init_rd_skt->bind(*(inst_153->target_0_rd_socket));
	}
	
	vitis_design_ps_e_0_sc*  inst_156=dynamic_cast<vitis_design_ps_e_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ps_e_0"));
	vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*  inst_157=dynamic_cast<vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0"));
	
	if(inst_156==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ps_e_0_sc"<<std::endl;
	}
	if(inst_157==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_interconnect_axihpm0fpd_upgraded_ipi_imp_xbar_0_sc"<<std::endl;
	}
	
	if (inst_156!=NULL && inst_157!=NULL) {
		inst_156->M_AXI_HPM0_FPD_wr_socket->bind(*(log_inst_21->tar_wr_skt));
		log_inst_21->init_wr_skt->bind(*(inst_157->target_0_wr_socket));
	}
	
}
#ifdef MTI_SYSTEMC
SC_MODULE_EXPORT(vitis_design_sci);
#endif

#ifdef XM_SYSTEMC
XMSC_MODULE_EXPORT(vitis_design_sci);
#endif

#ifdef RIVIERA
SC_MODULE_EXPORT(vitis_design_sci);
#endif

