APPNAME = disparity
TOP = cluster
HOST_SRCS = disparity.cpp
BRIDGE_SRCS = cluster_bridge_xrt.cpp
HOST_INCLUDES = -I$(SYSROOT)/usr/include/xrt
HOST_LIBS = -L$(SYSROOT)/usr/lib -lxrt_coreutil -lpthread

include ../Makefile