// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edgedetect_edgedetect_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_49_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        normal_factor_2_out,
        normal_factor_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] normal_factor_2_out;
output   normal_factor_2_out_ap_vld;

reg ap_idle;
reg normal_factor_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_101_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] convolve2d_smoothing_unsigned_char_unsigned_char_filter_address0;
wire   [7:0] convolve2d_smoothing_unsigned_char_unsigned_char_filter_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln51_fu_175_p1;
wire    ap_block_pp0_stage0;
reg   [5:0] normal_factor_2_fu_42;
wire   [5:0] normal_factor_fu_208_p2;
wire    ap_loop_init;
reg   [1:0] c_fu_46;
wire   [1:0] add_ln49_fu_180_p2;
reg   [1:0] ap_sig_allocacmp_c_load;
reg   [1:0] r_fu_50;
wire   [1:0] select_ln47_fu_139_p3;
reg   [1:0] ap_sig_allocacmp_r_load;
reg   [3:0] indvar_flatten20_fu_54;
wire   [3:0] add_ln47_fu_107_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten20_load;
wire    ap_block_pp0_stage0_01001;
reg    convolve2d_smoothing_unsigned_char_unsigned_char_filter_ce0_local;
wire   [0:0] icmp_ln49_fu_119_p2;
wire   [1:0] add_ln47_1_fu_133_p2;
wire   [3:0] p_shl_fu_151_p3;
wire   [3:0] zext_ln47_fu_147_p1;
wire   [1:0] select_ln31_fu_125_p3;
wire   [3:0] zext_ln49_fu_165_p1;
wire   [3:0] empty_fu_159_p2;
wire   [3:0] add_ln51_fu_169_p2;
wire   [5:0] trunc_ln51_fu_204_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 normal_factor_2_fu_42 = 6'd0;
#0 c_fu_46 = 2'd0;
#0 r_fu_50 = 2'd0;
#0 indvar_flatten20_fu_54 = 4'd0;
#0 ap_done_reg = 1'b0;
end

edgedetect_edgedetect_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_49_2_convolve2d_smoothing_unsibkb #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
convolve2d_smoothing_unsigned_char_unsigned_char_filter_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(convolve2d_smoothing_unsigned_char_unsigned_char_filter_address0),
    .ce0(convolve2d_smoothing_unsigned_char_unsigned_char_filter_ce0_local),
    .q0(convolve2d_smoothing_unsigned_char_unsigned_char_filter_q0)
);

edgedetect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_101_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_46 <= add_ln49_fu_180_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_46 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_101_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten20_fu_54 <= add_ln47_fu_107_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_54 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            normal_factor_2_fu_42 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            normal_factor_2_fu_42 <= normal_factor_fu_208_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_101_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_50 <= select_ln47_fu_139_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_50 <= 2'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_101_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 2'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten20_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten20_load = indvar_flatten20_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_load = 2'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        convolve2d_smoothing_unsigned_char_unsigned_char_filter_ce0_local = 1'b1;
    end else begin
        convolve2d_smoothing_unsigned_char_unsigned_char_filter_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_101_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        normal_factor_2_out_ap_vld = 1'b1;
    end else begin
        normal_factor_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_1_fu_133_p2 = (ap_sig_allocacmp_r_load + 2'd1);

assign add_ln47_fu_107_p2 = (ap_sig_allocacmp_indvar_flatten20_load + 4'd1);

assign add_ln49_fu_180_p2 = (select_ln31_fu_125_p3 + 2'd1);

assign add_ln51_fu_169_p2 = (zext_ln49_fu_165_p1 + empty_fu_159_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign convolve2d_smoothing_unsigned_char_unsigned_char_filter_address0 = zext_ln51_fu_175_p1;

assign empty_fu_159_p2 = (p_shl_fu_151_p3 - zext_ln47_fu_147_p1);

assign icmp_ln47_fu_101_p2 = ((ap_sig_allocacmp_indvar_flatten20_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_119_p2 = ((ap_sig_allocacmp_c_load == 2'd3) ? 1'b1 : 1'b0);

assign normal_factor_2_out = normal_factor_2_fu_42;

assign normal_factor_fu_208_p2 = (trunc_ln51_fu_204_p1 + normal_factor_2_fu_42);

assign p_shl_fu_151_p3 = {{select_ln47_fu_139_p3}, {2'd0}};

assign select_ln31_fu_125_p3 = ((icmp_ln49_fu_119_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_c_load);

assign select_ln47_fu_139_p3 = ((icmp_ln49_fu_119_p2[0:0] == 1'b1) ? add_ln47_1_fu_133_p2 : ap_sig_allocacmp_r_load);

assign trunc_ln51_fu_204_p1 = convolve2d_smoothing_unsigned_char_unsigned_char_filter_q0[5:0];

assign zext_ln47_fu_147_p1 = select_ln47_fu_139_p3;

assign zext_ln49_fu_165_p1 = select_ln31_fu_125_p3;

assign zext_ln51_fu_175_p1 = add_ln51_fu_169_p2;

endmodule //edgedetect_edgedetect_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_49_2
